services:
  db_local:
    container_name: nutrition-local-db
    env_file: ./.env.local
    extends:
      file: compose-db.yaml
      service: db
    volumes:
      - db-local-data:/var/lib/postgresql/data
volumes:
  db-local-data:
