services:
  server_local:
    container_name: nutrition-local-server
    env_file: ./.env.local
    extends:
      file: compose-server.yaml
      service: server
    volumes:
      - ./migrations/versions/:/app/migrations/versions/
