"""Add missing columns.

Revision ID: d7f38311778f
Revises: 69f70c579546
Create Date: 2023-12-04 16:31:28.108363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d7f38311778f"
down_revision = "69f70c579546"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingredient", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("brand", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("serving_unit_text", sa.String(), nullable=True))
        batch_op.alter_column(
            "serving_size",
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            existing_nullable=True,
        )

    with op.batch_alter_table("instruction", schema=None) as batch_op:
        batch_op.alter_column("index", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("recipe_id", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source", sa.String(), nullable=True))

    with op.batch_alter_table("recipe_ingredient", schema=None) as batch_op:
        batch_op.add_column(sa.Column("amount", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("amount_unit_text", sa.String(), nullable=True))
        batch_op.alter_column(
            "ingredient_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column("recipe_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_ingredient", schema=None) as batch_op:
        batch_op.alter_column("recipe_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "ingredient_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.drop_column("amount_unit_text")
        batch_op.drop_column("amount")

    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.drop_column("source")

    with op.batch_alter_table("instruction", schema=None) as batch_op:
        batch_op.alter_column("recipe_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("index", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("ingredient", schema=None) as batch_op:
        batch_op.alter_column(
            "serving_size",
            existing_type=sa.Float(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )
        batch_op.drop_column("serving_unit_text")
        batch_op.drop_column("brand")
        batch_op.drop_column("name")

    # ### end Alembic commands ###
